/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jtIMbYBIuQC
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Hero
 } from "./home/hero"
import { Features } from "./home/features"
export default function HomeComponent() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <center>
      <main className="flex-1">
        <Hero />
        <Features />
      </main>
      </center>
    </div>
  )
}




